lib: [
  "_build/install/default/lib/matrix_project/META"
  "_build/install/default/lib/matrix_project/Module/FloatField.ml" {"Module/FloatField.ml"}
  "_build/install/default/lib/matrix_project/Module/IntField.ml" {"Module/IntField.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeLinear.ml" {"Module/MakeLinear.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeMatrix.ml" {"Module/MakeMatrix.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeScalar.ml" {"Module/MakeScalar.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeTensor.ml" {"Module/MakeTensor.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeVSpace.ml" {"Module/MakeVSpace.ml"}
  "_build/install/default/lib/matrix_project/Module/MakeVecteur.ml" {"Module/MakeVecteur.ml"}
  "_build/install/default/lib/matrix_project/Module/Type/Dims.ml" {"Module/Type/Dims.ml"}
  "_build/install/default/lib/matrix_project/Module/Type/Field.ml" {"Module/Type/Field.ml"}
  "_build/install/default/lib/matrix_project/Module/Type/Nat_number.ml" {"Module/Type/Nat_number.ml"}
  "_build/install/default/lib/matrix_project/Module/Type/Vspace.ml" {"Module/Type/Vspace.ml"}
  "_build/install/default/lib/matrix_project/Module/Type/tensor.ml" {"Module/Type/tensor.ml"}
  "_build/install/default/lib/matrix_project/dune-package"
  "_build/install/default/lib/matrix_project/matrix_project.a"
  "_build/install/default/lib/matrix_project/matrix_project.cma"
  "_build/install/default/lib/matrix_project/matrix_project.cmi"
  "_build/install/default/lib/matrix_project/matrix_project.cmt"
  "_build/install/default/lib/matrix_project/matrix_project.cmx"
  "_build/install/default/lib/matrix_project/matrix_project.cmxa"
  "_build/install/default/lib/matrix_project/matrix_project.ml"
  "_build/install/default/lib/matrix_project/matrix_project__Module.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__FloatField.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__FloatField.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__FloatField.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__IntField.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__IntField.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__IntField.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeLinear.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeLinear.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeLinear.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeMatrix.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeMatrix.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeMatrix.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeScalar.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeScalar.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeScalar.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeTensor.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeTensor.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeTensor.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVSpace.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVSpace.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVSpace.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVecteur.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVecteur.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__MakeVecteur.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Dims.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Dims.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Dims.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Field.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Field.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Field.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Nat_number.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Nat_number.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Nat_number.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Tensor.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Tensor.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Tensor.cmx"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Vspace.cmi"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Vspace.cmt"
  "_build/install/default/lib/matrix_project/matrix_project__Module__Type__Vspace.cmx"
  "_build/install/default/lib/matrix_project/module/module.ml" {"module/module.ml"}
  "_build/install/default/lib/matrix_project/module/type/type.ml" {"module/type/type.ml"}
  "_build/install/default/lib/matrix_project/opam"
]
libexec: [
  "_build/install/default/lib/matrix_project/matrix_project.cmxs"
]
bin: [
  "_build/install/default/bin/matrix_project"
]
